version: '3.8'
name: paas-demo
services:
  transcryptor1:
    build: ..
    ports:
      - "8080:8080"
    depends_on:
      - redis1
    volumes:
      - ./public.pem:/resources/public.pem:ro
      - ./allowlist.yml:/resources/allowlist.yml:ro
      - ./server_config1.yml:/resources/server_config.yml:ro
    healthcheck:
      test: curl --fail http://0.0.0.0:8080/status || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    environment:
      REDIS_URL: redis://redis1:6379
  redis1:
    image: redis:alpine

  transcryptor2:
    build: ..
    ports:
      - "8081:8080"
    depends_on:
      - redis2
    volumes:
      - ./public.pem:/resources/public.pem:ro
      - ./allowlist.yml:/resources/allowlist.yml:ro
      - ./server_config2.yml:/resources/server_config.yml:ro
    healthcheck:
      test: curl --fail http://0.0.0.0:8080/status || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    environment:
      REDIS_URL: redis://redis2:6379
  redis2:
    image: redis:alpine

  transcryptor3:
    build: ..
    ports:
      - "8082:8080"
    depends_on:
      - redis3
    volumes:
      - ./public.pem:/resources/public.pem:ro
      - ./allowlist.yml:/resources/allowlist.yml:ro
      - ./server_config3.yml:/resources/server_config.yml:ro
    healthcheck:
      test: curl --fail http://0.0.0.0:8080/status || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    environment:
      REDIS_URL: redis://redis3:6379
  redis3:
    image: redis:alpine

