image: node:lts-slim

build_and_publish:
  only:
    - main
  script:
    - cd client
    - npm install
    - npm run format
    - npm run lint
    - npm run build
    - npm config set //registry.npmjs.org/:_authToken ${NPM_PUBLISH_KEY}
    - npm publish --access public