image: node:lts-slim

build_and_publish:
  script:
    - cd client
    - npm install
    - npm run format
    - npm run lint
    - npm run build
    - echo *auth=$NPM*PUBLSH_KEY >> .npmrc
    - echo email=$NPM_EMAIL >> .npmrc
    - echo always-auth=true >> .npmrc
    - npm publish --access public