build_and_publish:
  image: node:lts-slim

  only:
    - main
  when: manual
  script:
    - cd client/js
    - npm install
    - npm run format
    - npm run lint
    - npm run build
    - npm config set //registry.npmjs.org/:_authToken ${NPM_PUBLISH_KEY}
    - npm publish --access public


build-transcryptor-image:
    image: docker:27.4.0
    only:
        - main
    tags:
        - nolai_dind
    services: 
        - docker:27.4.0-dind
    variables: 
        DOCKER_TLS_CERTDIR: "/certs"
        IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH/paas-transcryptor:$CI_COMMIT_REF_SLUG
    before_script: 
        - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    script:
        - docker pull $IMAGE_TAG || true
        - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $IMAGE_TAG -t $IMAGE_TAG .
        - docker push $IMAGE_TAG
