build_and_publish:
  script:
    - apt-get update
    - apt-get install -y nodejs npm
    - npm install
    - npm run format
    - npm run lint
    - npm run build
    - echo *auth=$NPM*PUBLSH_KEY >> .npmrc
    - echo email=$NPM_EMAIL >> .npmrc
    - echo always-auth=true >> .npmrc
    - npm publish --access public