image: node:lts-slim

build_and_publish:
  script:
    - cd client
    - npm install
    - npm run format
    - npm run lint
    - npm run build
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
    - npm publish --access public