[workspace]
members = [
    "common",
    "server",
    "client/rs",
]
resolver = "2"

[workspace.dependencies]
libpep = "^0.6.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yml = "0.0.12"

[workspace.package]
authors = [
    "Job Doesburg <job@jobdoesburg.nl>",
    "Julian van der Horst <julian.vanderhorst@ru.nl"
]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/NOLAI/paas"
repository = "https://github.com/NOLAI/paas"