[package]
name = "paas_client"
version = "0.1.0"
edition = "2021"

[lib]
name = "paas_client"
path = "src/lib.rs"

[dependencies]
libpep = "^0.6.2"
paas_server = { path = "../../server" }
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4.39"
rand_core = "0.6.4"
mockito = "0.31.0"
tokio = { version = "1", features = ["full"] }
